alter table ADM_CASH_WARRANT add constraint FK_ADM_CASH_WARRANT_ON_CONTRACT foreign key (CONTRACT_ID) references ADM_CONTRACT(ID);
create index IDX_ADM_CASH_WARRANT_ON_CONTRACT on ADM_CASH_WARRANT (CONTRACT_ID);
