alter table ADM_CONTRACT add constraint FK_ADM_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references ADM_CONTRACTOR(ID);
create index IDX_ADM_CONTRACT_CONTRACTOR on ADM_CONTRACT (CONTRACTOR_ID);
