alter table ADM_CONTRACT_SERVICE_LINE add constraint FK_ADM_CONTRACT_SERVICE_LINE_SERVICE foreign key (SERVICE_ID) references ADM_SERVICE(ID);
create index IDX_ADM_CONTRACT_SERVICE_LINE_SERVICE on ADM_CONTRACT_SERVICE_LINE (SERVICE_ID);
