alter table ADM_CONTRACT_SERVICE_LINE_SERVICE_LINK add constraint FK_ACSLSL_CONTRACT_SERVICE_LINE foreign key (CONTRACT_SERVICE_LINE_ID) references ADM_CONTRACT_SERVICE_LINE(ID);
alter table ADM_CONTRACT_SERVICE_LINE_SERVICE_LINK add constraint FK_ACSLSL_SERVICE foreign key (SERVICE_ID) references ADM_SERVICE(ID);
