alter table ADM_CONTRACT add constraint FK_ADM_CONTRACT_RESPONSIBLE_MANAGER foreign key (RESPONSIBLE_MANAGER_ID) references SEC_USER(ID);
create index IDX_ADM_CONTRACT_RESPONSIBLE_MANAGER on ADM_CONTRACT (RESPONSIBLE_MANAGER_ID);
