alter table ADM_CONTRACT_SERVICE_LINE add constraint FK_ADM_CONTRACT_SERVICE_LINE_STATE foreign key (STATE_ID) references ADM_SERVICE_STATUS(ID);
alter table ADM_CONTRACT_SERVICE_LINE add constraint FK_ADM_CONTRACT_SERVICE_LINE_CONTRACT foreign key (CONTRACT_ID) references ADM_CONTRACT(ID);
create index IDX_ADM_CONTRACT_SERVICE_LINE_STATE on ADM_CONTRACT_SERVICE_LINE (STATE_ID);
create index IDX_ADM_CONTRACT_SERVICE_LINE_CONTRACT on ADM_CONTRACT_SERVICE_LINE (CONTRACT_ID);
