alter table ADM_SERVICE add constraint FK_ADM_SERVICE_SERVICE_STATUS foreign key (SERVICE_STATUS_ID) references ADM_SERVICE_STATUS(ID);
create index IDX_ADM_SERVICE_SERVICE_STATUS on ADM_SERVICE (SERVICE_STATUS_ID);
