alter table ADM_ANALYTICS_BANK_TICKET_LINE_LINK add constraint FK_AABTLL_ANALYTICS foreign key (ANALYTICS_ID) references ADM_ANALYTICS(ID);
alter table ADM_ANALYTICS_BANK_TICKET_LINE_LINK add constraint FK_AABTLL_BANK_TICKET_LINE foreign key (BANK_TICKET_LINE_ID) references ADM_BANK_TICKET_LINE(ID);
