alter table ADM_TICKET add constraint FK_ADM_TICKET_SOURCE_DESCRIPTION foreign key (SOURCE_DESCRIPTION_ID) references ADM_SOURCE_DESCRIPTION(ID);
create index IDX_ADM_TICKET_SOURCE_DESCRIPTION on ADM_TICKET (SOURCE_DESCRIPTION_ID);
