alter table ADM_BANK_TICKET_LINE add constraint FK_ADM_BANK_TICKET_LINE_ANALYTICS foreign key (ANALYTICS_ID) references ADM_ANALYTICS(ID);
create index IDX_ADM_BANK_TICKET_LINE_ANALYTICS on ADM_BANK_TICKET_LINE (ANALYTICS_ID);
