alter table ADM_SUITABLE_BANK add constraint FK_ADM_SUITABLE_BANK_ANALYTICS foreign key (ANALYTICS_ID) references ADM_ANALYTICS(ID);
create index IDX_ADM_SUITABLE_BANK_ANALYTICS on ADM_SUITABLE_BANK (ANALYTICS_ID);
