alter table ADM_CONTRACTOR_FILE_DESCRIPTOR_LINK add constraint FK_ACFDL_CONTRACTOR foreign key (CONTRACTOR_ID) references ADM_CONTRACTOR(ID);
alter table ADM_CONTRACTOR_FILE_DESCRIPTOR_LINK add constraint FK_ACFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
