alter table ADM_SOURCE_OF_INCOME add constraint FK_ADM_SOURCE_OF_INCOME_QUESTIONNAIRE foreign key (QUESTIONNAIRE_ID) references ADM_QUESTIONNAIRE(ID);
create index IDX_ADM_SOURCE_OF_INCOME_QUESTIONNAIRE on ADM_SOURCE_OF_INCOME (QUESTIONNAIRE_ID);
