alter table ADM_CURRENT_LOAN add constraint FK_ADM_CURRENT_LOAN_QUESTIONNAIRE foreign key (QUESTIONNAIRE_ID) references ADM_QUESTIONNAIRE(ID);
create index IDX_ADM_CURRENT_LOAN_QUESTIONNAIRE on ADM_CURRENT_LOAN (QUESTIONNAIRE_ID);
