alter table ADM_CURRENT_LOAN add constraint FK_ADM_CURRENT_LOAN_ANALYTICS foreign key (ANALYTICS_ID) references ADM_ANALYTICS(ID);
create index IDX_ADM_CURRENT_LOAN_ANALYTICS on ADM_CURRENT_LOAN (ANALYTICS_ID);
